version: "3"

services:
  frontend:
    image: "m0o3atef/complex-app-frontend"
    mem_limit: 128m

  api-server:
    image: "m0o3atef/complex-app-server"
    mem_limit: 128m
    environment:
      - REDISHOST=$REDISHOST
      - REDISPORT=$REDISPORT
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGHOST=$PGHOST
      - PGPORT=$PGPORT
      - PGDB=$PGDB

  worker:
    image: "m0o3atef/complex-app-worker"
    mem_limit: 128m
    environment:
      - REDISHOST=$REDISHOST
      - REDISPORT=$REDISPORT

  nginx:
    image: "m0o3atef/complex-app-nginx"
    mem_limit: 128m
    restart: always
    ports:
      - '80:80'
    depends_on:
      - api-server
      - frontend
