name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-test-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the test images
      run: docker build --file ./client/Dockerfile.dev --tag m0o3atef/complex-docker-frontend-dev ./client
    
    - name: Test the test images
      run: docker run -e CI=true m0o3atef/complex-docker-frontend npm run test
    
    - name: Build the prod images
      run: docker build --tag m0o3atef/complex-app-nginx ./nginx
      run: docker build --tag m0o3atef/complex-app-frontend ./client
      run: docker build --tag m0o3atef/complex-app-server ./server
      run: docker build --tag m0o3atef/complex-app-worker ./worker
    
    - name: Push the prod images
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
      run: docker push m0o3atef/complex-app-nginx
      run: docker push m0o3atef/complex-app-frontend
      run: docker push m0o3atef/complex-app-server
      run: docker push m0o3atef/complex-app-worker
    
    # - name: Generate deployment package
    #   run: zip -r deploy.zip . -x '*.git*'
    
    # - name: Deploy to EB
    #   uses: einaregilsson/beanstalk-deploy@v21
    #   with:
    #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
    #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
    #     application_name: udemy-frontend
    #     environment_name: udemy-frontend-env
    #     version_label: ${{ github.sha }}
    #     region: eu-north-1
    #     deployment_package: deploy.zip
    #     existing_bucket_name: elasticbeanstalk-eu-north-1-877533349104