name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the test images
      run: docker build -f ./client/Dockerfile.dev -t m0o3atef/complex-docker-frontend-dev ./client
    
    - name: Test the test images
      run: docker run -e CI=true m0o3atef/complex-docker-frontend-dev npm run test
  

  build-push:

    runs-on: ubuntu-latest
  
    needs: build-test
  
    steps:
    - name: Build the prod images
      run: | 
          docker build --tag m0o3atef/complex-app-nginx ./nginx
          docker build --tag m0o3atef/complex-app-frontend ./client
          docker build --tag m0o3atef/complex-app-server ./server
          docker build --tag m0o3atef/complex-app-worker ./worker
    
    - name: Push the prod images
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push m0o3atef/complex-app-nginx
          docker push m0o3atef/complex-app-frontend
          docker push m0o3atef/complex-app-server
          docker push m0o3atef/complex-app-worker
    
    # - name: Generate deployment package
    #   run: zip -r deploy.zip . -x '*.git*'
    
    # - name: Deploy to EB
    #   uses: einaregilsson/beanstalk-deploy@v21
    #   with:
    #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
    #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
    #     application_name: udemy-frontend
    #     environment_name: udemy-frontend-env
    #     version_label: ${{ github.sha }}
    #     region: eu-north-1
    #     deployment_package: deploy.zip
    #     existing_bucket_name: elasticbeanstalk-eu-north-1-877533349104